apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: deepjavatest-backend-jwt-secret
  namespace: storefront-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: deepagentdevops-dev/storefront-dev/JWT_SECRET
